import { expect, test } from '@playwright/test';

import { CHATUI_CONFIRM_KEY_GUARD_MS } from '../dist/runtime/store/confirm-store.js';

/**
 * Browser acceptance for the confirm dialog's keyboard model (DESIGN.md §6
 * 「确认与浮层」; INVARIANTS.md §15.1). decideConfirmKeyAction() /
 * nextConfirmFocusIndex() pin the *rules* without a DOM; the two things only a
 * real browser can answer are pinned here:
 *
 *   - Focus trap. `aria-modal="true"` is a claim until something keeps focus
 *     in the dialog. Before the trap, one Tab off the confirm button (the last
 *     focusable in the portal) landed on a host control behind the veil —
 *     invisible under the overlay. Only a real tab order can show that it no
 *     longer does.
 *   - Auto-repeat. `event.repeat` is generated by the browser's own key
 *     handling, and the failure it guards against (hold Enter down and the
 *     300ms window expires *underneath* the held key, so the next repeat
 *     confirms a deletion) only exists because a real focused <button> fires a
 *     native activation on every repeated keydown.
 *
 * The message-delete dialog is the fixture because it is the one confirm the
 * product opens from an ordinary chat surface and can leave again with nothing
 * changed. This spec is deliberately **non-mutating**: it answers the dialog
 * with cancel, so it neither depends on nor disturbs any other spec's view of
 * the shared disposable host (playwright-global-setup.mjs boots one ST for the
 * whole run). "Nothing was deleted" is itself one of the assertions.
 */

const MESSAGE_COUNT = 4;
/** A user message: not swipe-eligible, so its delete asks the two-way dialog. */
const TARGET_MESSAGE_ID = '0';
/** 删除 is tiled as a flat button on every turn row, so no menu is in the way. */
const DELETE_TILE_LABEL = '删除';
/** Long enough that the guard window closes *while the key is still held*. */
const HOLD_MS = CHATUI_CONFIRM_KEY_GUARD_MS * 3;
const HOLD_STEPS = 12;

/** Which control has focus, and whether it is still inside the dialog at all. */
async function readFocus(page) {
    return page.evaluate(() => {
        const active = document.activeElement;
        const card = document.querySelector('.cui-root-dialog');
        return {
            className: active instanceof HTMLElement ? active.className : null,
            text: active instanceof HTMLElement ? active.textContent?.trim() ?? '' : null,
            insideDialog: Boolean(card && active && card.contains(active)),
        };
    });
}

/** Every direct child of <body>, and whether the dialog took it out of play. */
async function readBackgroundIsolation(page) {
    return page.evaluate(() => {
        const overlay = document.querySelector('.cui-root-dialog-overlay');
        return Array.from(document.body.children).map(child => ({
            name: child.id || child.className || child.tagName,
            isDialogPortal: Boolean(overlay && (child === overlay || child.contains(overlay))),
            inert: child.inert === true,
        }));
    });
}

test('the delete confirm dialog traps focus, takes the page behind it out of play, and refuses a held Enter', async ({ page }, testInfo) => {
    const pageErrors = [];
    const chatuiConsoleErrors = [];
    page.on('pageerror', error => pageErrors.push(error.stack ?? error.message));
    page.on('console', message => {
        if (message.type() === 'error' && message.text().includes('[ChatUI]')) {
            chatuiConsoleErrors.push(message.text());
        }
    });

    const url = process.env.SILLYLOUNGE_E2E_URL;
    expect(url, 'global setup must expose the disposable ST URL').toBeTruthy();
    await page.goto(url, { waitUntil: 'domcontentloaded' });

    const root = page.locator('#chatui-root[data-cui-root-mounted="1"]');
    await expect(root).toBeVisible();
    const messages = root.locator('.cui-root-message-list article.cui-root-message');
    await expect(messages).toHaveCount(MESSAGE_COUNT);

    // This scenario is about the dialog, so a host that would skip the dialog
    // entirely has to fail loudly rather than quietly pass an empty test.
    await expect.poll(() => page.evaluate(() => (
        globalThis.SillyTavern?.getContext?.().powerUserSettings?.confirm_message_delete
    )), { message: 'the host\'s confirm-on-delete gate must be on for this fixture' }).toBe(true);

    // Records what the browser actually delivered, so "the dialog stayed open
    // while Enter was held" cannot pass vacuously on a run where no auto-repeat
    // ever arrived. Registered at window capture *before* the dialog mounts, so
    // the dialog's own capture listener (which stops propagation, not immediate
    // propagation) cannot hide events from it.
    await page.evaluate(() => {
        globalThis.__loungeKeyLog = [];
        window.addEventListener('keydown', event => {
            globalThis.__loungeKeyLog.push({ key: event.key, repeat: event.repeat });
        }, true);
    });

    const message = root.locator(`[data-cui-message-id="${TARGET_MESSAGE_ID}"]`);
    await message.hover();
    const deleteButton = message.getByRole('button', { name: DELETE_TILE_LABEL, exact: true });
    await deleteButton.focus();

    // ── The held Enter ───────────────────────────────────────────────────────
    // The first keydown is a real, deliberate activation of the focused Delete
    // button: repeat === false, and it opens the dialog. The key is then never
    // released, so everything after it is the same physical press.
    await page.keyboard.down('Enter');
    const dialog = page.locator('.cui-root-dialog');
    await expect(dialog).toBeVisible();
    await expect(dialog.locator('.cui-root-dialog-title')).toHaveText('删除这一楼？');
    const buttons = dialog.locator('.cui-root-dialog-btn');
    await expect(buttons).toHaveCount(2, 'a user message is not swipe-eligible, so this is the two-way dialog');

    for (let step = 0; step < HOLD_STEPS; step += 1) {
        // Playwright marks a `down` on an already-pressed key as an auto-repeat,
        // which is exactly what the browser does for a held key.
        await page.keyboard.down('Enter');
        await page.waitForTimeout(Math.ceil(HOLD_MS / HOLD_STEPS));
    }
    // Not a settle heuristic: the wait above *is* the guard window, deliberately
    // outlived while the key is still down. That is the whole failure mode —
    // before the repeat rule, this is the moment the deletion went through.
    const heldKeyLog = await page.evaluate(() => globalThis.__loungeKeyLog);
    expect(
        heldKeyLog.filter(entry => entry.key === 'Enter' && entry.repeat).length,
        'the browser must actually have delivered auto-repeated Enters for this to prove anything',
    ).toBeGreaterThan(0);

    await expect(dialog).toBeVisible();
    await expect.poll(() => page.evaluate(() => (
        globalThis.SillyTavern?.getContext?.().chat?.length
    )), { message: 'a held Enter must never delete a message' }).toBe(MESSAGE_COUNT);
    await page.keyboard.up('Enter');

    // ── Focus, and the page behind the veil ──────────────────────────────────
    const openedFocus = await readFocus(page);
    expect(openedFocus.className).toContain('cui-root-dialog-confirm');
    expect(openedFocus.insideDialog).toBe(true);

    const isolatedBackground = await readBackgroundIsolation(page);
    expect(isolatedBackground.some(child => child.isDialogPortal), 'the dialog portals to <body>').toBe(true);
    for (const child of isolatedBackground) {
        expect(child.inert, `<body> child ${child.name} while the dialog is open`).toBe(!child.isDialogPortal);
    }

    // ── The trap ─────────────────────────────────────────────────────────────
    // Source order is 取消 then 删除, and focus opens on 删除 (the last), so a
    // forward Tab has to wrap. Two full laps plus one, to catch a trap that
    // only holds for the first cycle.
    const forwardLap = [];
    for (let press = 0; press < 5; press += 1) {
        await page.keyboard.press('Tab');
        const focus = await readFocus(page);
        expect(focus.insideDialog, `Tab #${press + 1} must leave focus inside the dialog`).toBe(true);
        forwardLap.push(focus.text);
    }
    expect(forwardLap).toEqual(['取消', '删除', '取消', '删除', '取消']);

    const backwardLap = [];
    for (let press = 0; press < 3; press += 1) {
        await page.keyboard.press('Shift+Tab');
        const focus = await readFocus(page);
        expect(focus.insideDialog, `Shift+Tab #${press + 1} must leave focus inside the dialog`).toBe(true);
        backwardLap.push(focus.text);
    }
    expect(backwardLap).toEqual(['删除', '取消', '删除']);

    await testInfo.attach('confirm-dialog-open', {
        body: await page.screenshot(),
        contentType: 'image/png',
    });

    // ── One deliberate keystroke still answers ───────────────────────────────
    // Nothing above may have cost the dialog its ordinary keyboard behaviour:
    // walk to 取消 with the trap and activate it with a fresh (repeat === false,
    // guard long expired) Enter. The cancel button is the non-destructive half
    // of the same "the focused control answers for itself" path the confirm
    // button takes.
    await page.keyboard.press('Shift+Tab');
    expect((await readFocus(page)).text).toBe('取消');
    await page.keyboard.press('Enter');
    await expect(dialog).toHaveCount(0);

    // ── What the dialog left behind ──────────────────────────────────────────
    await expect(messages).toHaveCount(MESSAGE_COUNT);
    await expect.poll(() => page.evaluate(() => (
        globalThis.SillyTavern?.getContext?.().chat?.length
    ))).toBe(MESSAGE_COUNT);

    const restoredBackground = await readBackgroundIsolation(page);
    for (const child of restoredBackground) {
        expect(child.inert, `<body> child ${child.name} after the dialog closed`).toBe(false);
    }
    // Focus goes back where it came from rather than stranding a keyboard user
    // on <body> — the Delete button is still there, since nothing was deleted.
    const restoredFocus = await readFocus(page);
    expect(restoredFocus.className).toContain('cui-root-action-btn');
    expect(await deleteButton.evaluate(element => element === document.activeElement)).toBe(true);

    expect(pageErrors, `page errors:\n${pageErrors.join('\n')}`).toEqual([]);
    expect(chatuiConsoleErrors, `ChatUI console errors:\n${chatuiConsoleErrors.join('\n')}`).toEqual([]);
});
